import React, { useContext, useMemo } from 'react';
import {
  compileContentComponent,
  ContentContext,
} from '../../../../../shared/content';
import { formatGpuField, getGpuName } from '../../../..';
import { ViewPageContext } from '../../context';

const PowerSupplyBlurbSentence1 = compileContentComponent({
  deps: ['company', 'psu'],
  component: (props) => (
    <>
      {props.company} recommends a power supply of at least {props.psu}. Using a
      power supply lower than this can result in system crashes or your computer
      shutting off and potentially damaging your hardware.
    </>
  ),
});

const PowerSupplyBlurbSentence2 = compileContentComponent({
  deps: ['tdp'],
  component: (props) => (
    <>
      This graphics card has a Thermal Design Power (TDP) of {props.tdp}. This
      is the maximum amount of heat generated by the GPU. A higher TDP usually
      implies better performance. However, this produces more heat and requires
      a stronger cooling system.
    </>
  ),
});

export const PowerSupplyBlurb = () => {
  const { gpu } = useContext(ViewPageContext);

  const context = useMemo(() => {
    const params = {
      company: formatGpuField(gpu.company),
      psu: formatGpuField(gpu.specs?.suggestedPsu),
      shortGpuName: getGpuName(gpu, { company: false }),
      tdp: formatGpuField(gpu.specs?.thermalDesignPower),
    };

    return { params };
  }, [gpu]);

  return (
    <ContentContext.Provider value={context}>
      <p>
        <PowerSupplyBlurbSentence1 />
      </p>

      <p>
        <PowerSupplyBlurbSentence2 />
      </p>
    </ContentContext.Provider>
  );
};
