import {
  ClockSpeedUnit,
  CurrencyUnit,
  LengthUnit,
  MeasurementUnit,
  MemorySizeUnit,
  NumericUnit,
  TemperatureUnit,
  WattageUnit,
} from '@pcpartdb/shared';

export const MEASUREMENT_UNITS: Record<string, MeasurementUnit[]> = {
  baseClock: [ClockSpeedUnit.mhz],
  clock: [ClockSpeedUnit.ghz, ClockSpeedUnit.mhz],
  turboClock: [ClockSpeedUnit.ghz, ClockSpeedUnit.mhz],
  performanceCoreClock: [ClockSpeedUnit.ghz, ClockSpeedUnit.mhz],
  performanceCoreTurboClock: [ClockSpeedUnit.ghz, ClockSpeedUnit.mhz],
  efficientCoreClock: [ClockSpeedUnit.ghz, ClockSpeedUnit.mhz],
  efficientCoreTurboClock: [ClockSpeedUnit.ghz, ClockSpeedUnit.mhz],
  l1Cache: [MemorySizeUnit.kb, MemorySizeUnit.mb],
  l2Cache: [MemorySizeUnit.kb, MemorySizeUnit.mb],
  l3Cache: [MemorySizeUnit.kb, MemorySizeUnit.mb],
  efficientCoreL1Cache: [MemorySizeUnit.kb, MemorySizeUnit.mb],
  efficientCoreL2Cache: [MemorySizeUnit.kb, MemorySizeUnit.mb],
  launchPrice: [CurrencyUnit.USD],
  processSize: [LengthUnit.nm, LengthUnit.um],
  transistors: [NumericUnit.million],
  tdp: [WattageUnit.w],
  pl1: [WattageUnit.w],
  pl2: [WattageUnit.w],
  ppt: [WattageUnit.w],
  tCaseMax: [TemperatureUnit.c],
  tjMax: [TemperatureUnit.c],
};
