version: "3.8"

services:
  db:
    image: postgres:16-alpine
    container_name: pcpartdb-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  db-data:
    driver: local

