version: '2.1'

services:
  db:
    image: timescale/timescaledb:latest-pg12
    container_name: finestpc-db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - ./.env

volumes:
  db-data:
    driver: local
