server {
        server_name pcpartdb.com;
        root /srv/web/pcpartdb/public;

        listen 443 ssl http2;
        listen [::]:443 ssl ipv6only=on http2;

        ssl_certificate /etc/cloudflare/certs/cert.pem;
        ssl_certificate_key /etc/cloudflare/certs/key.pem;

        client_max_body_size 10M;

        location / {
          include proxy_params;
          proxy_pass http://localhost:3010;
        }
}

server {
        server_name www.pcpartdb.com;

        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        return 301 https://pcpartdb.com$request_uri;
}